/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readUser"];
        put: operations["updateUser"];
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readSession"];
        put: operations["updateSession"];
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readSessionTemplate"];
        put: operations["updateSessionTemplate"];
        post?: never;
        delete: operations["deleteSessionTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/active/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["endActiveSession"];
        post?: never;
        delete: operations["deleteActiveSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSessionTemplates"];
        put?: never;
        post: operations["createSessionTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSetTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExerciseTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHomePage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/templates/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startSessionTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/request/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sendRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/reject/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rejectRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/accept/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["acceptRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserRequestDTO: {
            userName?: string;
            password?: string;
        };
        UserResponseDTO: {
            /** Format: int64 */
            id?: number;
            userName?: string;
        };
        ExerciseRequestDTO: {
            /** @enum {string} */
            type?: ExerciseRequestDTOType;
            description?: string;
            sets?: components["schemas"]["SetRequestDTO"][];
        };
        SessionRequestDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            exercises?: components["schemas"]["ExerciseRequestDTO"][];
        };
        SetRequestDTO: {
            /** @enum {string} */
            type?: SetRequestDTOType;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weight?: number;
        };
        ExerciseResponseDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: ExerciseResponseDTOType;
            description?: string;
            sets?: components["schemas"]["SetResponseDTO"][];
        };
        SessionResponseDTO: {
            /** Format: int64 */
            id?: number;
            user?: components["schemas"]["UserResponseDTO"];
            /** Format: double */
            volume?: number;
            name?: string;
            description?: string;
            exercises?: components["schemas"]["ExerciseResponseDTO"][];
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
        };
        SetResponseDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: SetResponseDTOType;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weight?: number;
        };
        TemplateExerciseRequestDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: TemplateExerciseRequestDTOType;
            sets?: components["schemas"]["TemplateSetRequestDTO"][];
        };
        TemplateSessionRequestDTO: {
            name?: string;
            exercises?: components["schemas"]["TemplateExerciseRequestDTO"][];
        };
        TemplateSetRequestDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: TemplateSetRequestDTOType;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weight?: number;
        };
        TemplateExerciseResponseDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: TemplateExerciseResponseDTOType;
            sets?: components["schemas"]["SetResponseDTO"][];
        };
        TemplateSessionResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            exercises?: components["schemas"]["TemplateExerciseResponseDTO"][];
        };
        ActiveExerciseRequestDTO: {
            /** Format: int64 */
            id?: number;
            description?: string;
            /** @enum {string} */
            type?: ActiveExerciseRequestDTOType;
            sets?: components["schemas"]["ActiveSetRequestDTO"][];
        };
        ActiveSessionRequestDTO: {
            name?: string;
            description?: string;
            exercises?: components["schemas"]["ActiveExerciseRequestDTO"][];
            /** Format: date-time */
            start?: string;
            public?: boolean;
        };
        ActiveSetRequestDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: ActiveSetRequestDTOType;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weight?: number;
        };
        UserRelationResponseDTO: {
            /** Format: int64 */
            id?: number;
            userName?: string;
            canAdd?: boolean;
            canAccept?: boolean;
        };
        UserTypeDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: UserTypeDTOType;
        };
        SetTypeDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: SetTypeDTOType;
        };
        ExerciseTypeDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: ExerciseTypeDTOType;
        };
        SessionOverviewResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            exercises?: SessionOverviewResponseDTOExercises[];
        };
        ActiveExerciseResponseDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: ActiveExerciseResponseDTOType;
            sets?: components["schemas"]["SetResponseDTO"][];
        };
        ActiveSessionResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            exercises?: components["schemas"]["ActiveExerciseResponseDTO"][];
            /** Format: date-time */
            start?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserRelationResponseDTO"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    readSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponseDTO"];
                };
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponseDTO"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    readSessionTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateSessionResponseDTO"];
                };
            };
        };
    };
    updateSessionTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateSessionRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateSessionResponseDTO"];
                };
            };
        };
    };
    deleteSessionTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    endActiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveSessionRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponseDTO"];
                };
            };
        };
    };
    deleteActiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getSessionTemplates: {
        parameters: {
            query: {
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionOverviewResponseDTO"][];
                };
            };
        };
    };
    createSessionTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateSessionRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateSessionResponseDTO"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getUserTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserTypeDTO"][];
                };
            };
        };
    };
    getSetTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetTypeDTO"][];
                };
            };
        };
    };
    getExerciseTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseTypeDTO"][];
                };
            };
        };
    };
    getHomePage: {
        parameters: {
            query: {
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponseDTO"][];
                };
            };
        };
    };
    getUserSessions: {
        parameters: {
            query: {
                offset: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponseDTO"][];
                };
            };
        };
    };
    startSessionTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActiveSessionResponseDTO"];
                };
            };
        };
    };
    getActiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActiveSessionResponseDTO"];
                };
            };
        };
    };
    sendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    rejectRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    acceptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
export enum ExerciseRequestDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum SetRequestDTOType {
    NORMAL = "NORMAL",
    WARM_UP = "WARM_UP",
    FAILURE = "FAILURE",
    DROP_SET = "DROP_SET",
    SUPER_SET = "SUPER_SET"
}
export enum ExerciseResponseDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum SetResponseDTOType {
    NORMAL = "NORMAL",
    WARM_UP = "WARM_UP",
    FAILURE = "FAILURE",
    DROP_SET = "DROP_SET",
    SUPER_SET = "SUPER_SET"
}
export enum TemplateExerciseRequestDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum TemplateSetRequestDTOType {
    NORMAL = "NORMAL",
    WARM_UP = "WARM_UP",
    FAILURE = "FAILURE",
    DROP_SET = "DROP_SET",
    SUPER_SET = "SUPER_SET"
}
export enum TemplateExerciseResponseDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum ActiveExerciseRequestDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum ActiveSetRequestDTOType {
    NORMAL = "NORMAL",
    WARM_UP = "WARM_UP",
    FAILURE = "FAILURE",
    DROP_SET = "DROP_SET",
    SUPER_SET = "SUPER_SET"
}
export enum UserTypeDTOType {
    ME = "ME",
    OTHER = "OTHER",
    FRIEND = "FRIEND"
}
export enum SetTypeDTOType {
    NORMAL = "NORMAL",
    WARM_UP = "WARM_UP",
    FAILURE = "FAILURE",
    DROP_SET = "DROP_SET",
    SUPER_SET = "SUPER_SET"
}
export enum ExerciseTypeDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum SessionOverviewResponseDTOExercises {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
export enum ActiveExerciseResponseDTOType {
    BARBELL_BENCH_PRESS = "BARBELL_BENCH_PRESS",
    DUMBBELL_BENCH_PRESS = "DUMBBELL_BENCH_PRESS",
    INCLINE_BENCH_PRESS = "INCLINE_BENCH_PRESS",
    DECLINE_BENCH_PRESS = "DECLINE_BENCH_PRESS",
    CHEST_FLY_DUMBBELL = "CHEST_FLY_DUMBBELL",
    PEC_DECK_MACHINE = "PEC_DECK_MACHINE",
    CHEST_PRESS_MACHINE = "CHEST_PRESS_MACHINE",
    CABLE_CROSSOVER = "CABLE_CROSSOVER",
    PUSH_UP = "PUSH_UP",
    DIPS = "DIPS",
    PULL_UP = "PULL_UP",
    CHIN_UP = "CHIN_UP",
    LAT_PULLDOWN = "LAT_PULLDOWN",
    BARBELL_ROW = "BARBELL_ROW",
    DUMBBELL_ROW = "DUMBBELL_ROW",
    SEATED_CABLE_ROW = "SEATED_CABLE_ROW",
    T_BAR_ROW = "T_BAR_ROW",
    MACHINE_ROW = "MACHINE_ROW",
    DEADLIFT = "DEADLIFT",
    HYPEREXTENSION = "HYPEREXTENSION",
    OVERHEAD_PRESS_BARBELL = "OVERHEAD_PRESS_BARBELL",
    OVERHEAD_PRESS_DUMBBELL = "OVERHEAD_PRESS_DUMBBELL",
    SHOULDER_PRESS_MACHINE = "SHOULDER_PRESS_MACHINE",
    ARNOLD_PRESS = "ARNOLD_PRESS",
    LATERAL_RAISE_DUMBBELL = "LATERAL_RAISE_DUMBBELL",
    LATERAL_RAISE_MACHINE = "LATERAL_RAISE_MACHINE",
    FRONT_RAISE = "FRONT_RAISE",
    REAR_DELT_FLY = "REAR_DELT_FLY",
    FACE_PULL = "FACE_PULL",
    UPRIGHT_ROW = "UPRIGHT_ROW",
    BARBELL_BICEPS_CURL = "BARBELL_BICEPS_CURL",
    DUMBBELL_BICEPS_CURL = "DUMBBELL_BICEPS_CURL",
    HAMMER_CURL = "HAMMER_CURL",
    PREACHER_CURL_MACHINE = "PREACHER_CURL_MACHINE",
    CABLE_BICEPS_CURL = "CABLE_BICEPS_CURL",
    TRICEPS_PUSH_DOWN = "TRICEPS_PUSH_DOWN",
    SKULL_CRUSHER = "SKULL_CRUSHER",
    OVERHEAD_TRICEPS_EXTENSION = "OVERHEAD_TRICEPS_EXTENSION",
    TRICEPS_DIP = "TRICEPS_DIP",
    TRICEPS_EXTENSION_MACHINE = "TRICEPS_EXTENSION_MACHINE",
    BARBELL_SQUAT = "BARBELL_SQUAT",
    FRONT_SQUAT = "FRONT_SQUAT",
    LEG_PRESS_MACHINE = "LEG_PRESS_MACHINE",
    HACK_SQUAT_MACHINE = "HACK_SQUAT_MACHINE",
    LUNGES = "LUNGES",
    LEG_EXTENSION = "LEG_EXTENSION",
    LEG_CURL = "LEG_CURL",
    ROMANIAN_DEADLIFT = "ROMANIAN_DEADLIFT",
    CALF_RAISE_STANDING = "CALF_RAISE_STANDING",
    CALF_RAISE_SEATED = "CALF_RAISE_SEATED",
    HIP_THRUST = "HIP_THRUST",
    GLUTE_BRIDGE = "GLUTE_BRIDGE",
    PLANK = "PLANK",
    SIDE_PLANK = "SIDE_PLANK",
    CRUNCH = "CRUNCH",
    CABLE_CRUNCH = "CABLE_CRUNCH",
    LEG_RAISE = "LEG_RAISE",
    HANGING_LEG_RAISE = "HANGING_LEG_RAISE",
    RUSSIAN_TWIST = "RUSSIAN_TWIST",
    AB_WHEEL_ROLLOUT = "AB_WHEEL_ROLLOUT",
    BACK_EXTENSION_MACHINE = "BACK_EXTENSION_MACHINE",
    TREADMILL = "TREADMILL",
    STATIONARY_BIKE = "STATIONARY_BIKE",
    SPIN_BIKE = "SPIN_BIKE",
    ELLIPTICAL = "ELLIPTICAL",
    STAIR_CLIMBER = "STAIR_CLIMBER",
    ROWING_MACHINE = "ROWING_MACHINE"
}
